apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deploy
spec:
  selector:
    matchLabels:
      app: app1
  replicas: 1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: zahirul012/laravel-app1
        ports:
        - containerPort: 8000
      tolerations:
      - key: "app1"
        operator: "Equal"
        value: "app1"
        effect: "NoSchedule"     
---
apiVersion: v1
kind: Service
metadata:
  name: app1-svc
spec:
  type: NodePort
  selector:
    app: app1
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30007
 
